name: Voyager - Maestro tests
on: 
  workflow_dispatch:
  pull_request:
jobs:
  uitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Maestro 1
        uses: './'
        with:
          apk-path: './sample/voyager-debug.apk'
          command: 'maestro test ./sample/android-voyager-flow.yaml'
          report-name: 'report1'
          record: 'true'

      - name: Run Maestro 2
        uses: './'
        with:
          apk-path: './sample/voyager-debug.apk'
          report-name: 'report2'
          command: 'maestro test ./sample/android-voyager-flow.yaml'
          record: 'false'

      - name: Run Maestro 3
        uses: './'
        with:
          apk-path: './sample/voyager-debug.apk'
          report-name: 'report3'
          command: 'maestro test --format junit --output ~/teste.xml ./sample/android-voyager-flow.yaml'