name: Maestro tests
on: 
  workflow_dispatch:
  pull_request:
jobs:
  uitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Maestro
        uses: './'
        with:
          apk-path: './sample/voyager-debug.apk'
          command: 'maestro test ./sample/android-voyager-flow.yaml'
          report-name: 'report1'
          record: 'true'
